[tool.poetry]
name = "pypixiv"
version = "0.0.1"
description = "python pixiv api wrapper"
authors = [
    "DeltaLaboratory <delta@deltalab.dev>"
]

[tool.poetry.dependencies]
python = "^3.10"

pydantic = "^1.9.0"
httpx = "^0.21.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
