[tool.poetry]
name = "pypixiv"
version = "0.0.1"
description = "python pixiv api wrapper"
authors = [
    "DeltaLaboratory <delta@deltalab.dev>"
]

[tool.poetry.dependencies]
python = "^3.10"

pydantic = "^1.9.0"
httpx = "^0.21.3"
h2 = "^4.1.0"

[tool.poetry.dev-dependencies]
ipython = "^8.0.0"
mypy = "^0.931"
pytest = "^6.2.5"
pytest-asyncio = "^0.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
